"""
Career Path Definitions — CareerIQ
------------------------------------
80+ careers across 8 industries.
Every career has:
  required:     must-have skills (weight 3x)
  important:    strong signal skills (weight 2x)
  nice_to_have: bonus skills (weight 1x)
  avg_salary:   USD median
  growth:       YoY demand estimate
  description:  plain English summary
  industry:     category label
"""

CAREER_PATHS = {

    # ── DATA & ANALYTICS ──────────────────────────────────────────────────────
    "Data Analyst": {
        "industry": "Data & Analytics",
        "description": "Analyze data to surface business insights using SQL, spreadsheets, and BI tools.",
        "avg_salary": 78000, "growth": "+18%",
        "required":     ["sql", "excel", "data analysis", "data visualization"],
        "important":    ["python", "tableau", "power bi", "statistics"],
        "nice_to_have": ["r", "machine learning", "looker", "a/b testing"],
    },
    "Business Analyst": {
        "industry": "Data & Analytics",
        "description": "Bridge business needs and data/tech solutions through analysis and communication.",
        "avg_salary": 82000, "growth": "+14%",
        "required":     ["sql", "excel", "business analysis", "requirements gathering"],
        "important":    ["tableau", "power bi", "statistics", "project management"],
        "nice_to_have": ["python", "agile", "financial modeling", "process mapping"],
    },
    "Data Scientist": {
        "industry": "Data & Analytics",
        "description": "Build statistical models and ML systems to solve complex business problems.",
        "avg_salary": 115000, "growth": "+35%",
        "required":     ["python", "machine learning", "statistics", "sql"],
        "important":    ["pandas", "numpy", "scikit-learn", "data visualization"],
        "nice_to_have": ["deep learning", "tensorflow", "pytorch", "aws", "spark"],
    },
    "Data Engineer": {
        "industry": "Data & Analytics",
        "description": "Build the data infrastructure — pipelines, warehouses, and lakes — that powers analytics.",
        "avg_salary": 118000, "growth": "+30%",
        "required":     ["python", "sql", "etl", "data pipeline"],
        "important":    ["spark", "airflow", "aws", "postgresql", "docker"],
        "nice_to_have": ["kafka", "dbt", "snowflake", "databricks", "scala"],
    },
    "Analytics Engineer": {
        "industry": "Data & Analytics",
        "description": "Transform raw data into clean, reliable datasets using SQL and dbt.",
        "avg_salary": 105000, "growth": "+28%",
        "required":     ["sql", "dbt", "data warehouse", "python"],
        "important":    ["snowflake", "databricks", "git", "data visualization"],
        "nice_to_have": ["spark", "looker", "statistics", "aws", "etl"],
    },
    "Product Analyst": {
        "industry": "Data & Analytics",
        "description": "Use data to understand user behavior and drive product decisions.",
        "avg_salary": 90000, "growth": "+20%",
        "required":     ["sql", "data analysis", "a/b testing", "statistics"],
        "important":    ["python", "tableau", "excel", "data visualization"],
        "nice_to_have": ["machine learning", "r", "looker", "product management"],
    },
    "Business Intelligence Developer": {
        "industry": "Data & Analytics",
        "description": "Design and maintain BI dashboards and reporting infrastructure.",
        "avg_salary": 95000, "growth": "+16%",
        "required":     ["sql", "tableau", "power bi", "data warehousing"],
        "important":    ["python", "excel", "etl", "data modeling"],
        "nice_to_have": ["looker", "dbt", "aws", "snowflake"],
    },

    # ── MACHINE LEARNING & AI ─────────────────────────────────────────────────
    "ML Engineer": {
        "industry": "Machine Learning & AI",
        "description": "Build, train, and deploy machine learning models at scale in production.",
        "avg_salary": 130000, "growth": "+42%",
        "required":     ["python", "machine learning", "deep learning", "sql"],
        "important":    ["tensorflow", "pytorch", "docker", "aws", "git"],
        "nice_to_have": ["kubernetes", "spark", "mlops", "scala", "kafka"],
    },
    "AI Engineer": {
        "industry": "Machine Learning & AI",
        "description": "Build and integrate AI/LLM-powered applications and systems.",
        "avg_salary": 145000, "growth": "+85%",
        "required":     ["python", "large language models", "prompt engineering", "machine learning"],
        "important":    ["deep learning", "pytorch", "aws", "rest api", "docker"],
        "nice_to_have": ["rag", "fine-tuning", "kubernetes", "generative ai", "mlops"],
    },
    "NLP Engineer": {
        "industry": "Machine Learning & AI",
        "description": "Specialize in natural language processing: text classification, summarization, translation.",
        "avg_salary": 135000, "growth": "+55%",
        "required":     ["python", "nlp", "machine learning", "deep learning"],
        "important":    ["transformers", "pytorch", "hugging face", "sql"],
        "nice_to_have": ["large language models", "rag", "spark", "aws"],
    },
    "Computer Vision Engineer": {
        "industry": "Machine Learning & AI",
        "description": "Build systems that analyze and interpret visual data — images, video, real-time streams.",
        "avg_salary": 138000, "growth": "+48%",
        "required":     ["python", "computer vision", "deep learning", "machine learning"],
        "important":    ["pytorch", "tensorflow", "opencv", "aws"],
        "nice_to_have": ["cuda", "docker", "c++", "robotics"],
    },
    "Quantitative Analyst": {
        "industry": "Machine Learning & AI",
        "description": "Apply advanced math and statistics to financial modeling and risk analysis.",
        "avg_salary": 135000, "growth": "+12%",
        "required":     ["python", "statistics", "linear algebra", "sql"],
        "important":    ["r", "machine learning", "time series", "quantitative analysis"],
        "nice_to_have": ["scala", "matlab", "deep learning", "monte carlo"],
    },
    "Research Scientist (AI)": {
        "industry": "Machine Learning & AI",
        "description": "Advance the state of the art in AI through original research and publications.",
        "avg_salary": 160000, "growth": "+60%",
        "required":     ["python", "deep learning", "machine learning", "research methodology"],
        "important":    ["pytorch", "tensorflow", "statistics", "linear algebra", "academic writing"],
        "nice_to_have": ["cuda", "distributed systems", "reinforcement learning", "publications"],
    },

    # ── SOFTWARE ENGINEERING ──────────────────────────────────────────────────
    "Software Engineer": {
        "industry": "Software Engineering",
        "description": "Design and build software systems, APIs, and applications.",
        "avg_salary": 110000, "growth": "+25%",
        "required":     ["python", "git", "sql", "data structures"],
        "important":    ["javascript", "rest api", "docker", "aws", "linux"],
        "nice_to_have": ["kubernetes", "typescript", "microservices", "ci/cd"],
    },
    "Frontend Engineer": {
        "industry": "Software Engineering",
        "description": "Build user-facing web interfaces with modern JavaScript frameworks.",
        "avg_salary": 105000, "growth": "+22%",
        "required":     ["javascript", "html", "css", "react"],
        "important":    ["typescript", "git", "rest api", "responsive design"],
        "nice_to_have": ["vue", "angular", "webpack", "testing", "accessibility"],
    },
    "Backend Engineer": {
        "industry": "Software Engineering",
        "description": "Build server-side logic, databases, and APIs that power applications.",
        "avg_salary": 115000, "growth": "+24%",
        "required":     ["python", "sql", "rest api", "git"],
        "important":    ["docker", "aws", "postgresql", "linux", "microservices"],
        "nice_to_have": ["kubernetes", "redis", "kafka", "go", "grpc"],
    },
    "Full Stack Engineer": {
        "industry": "Software Engineering",
        "description": "Build both the frontend and backend of web applications end-to-end.",
        "avg_salary": 112000, "growth": "+26%",
        "required":     ["javascript", "python", "sql", "git", "rest api"],
        "important":    ["react", "node.js", "docker", "postgresql", "aws"],
        "nice_to_have": ["typescript", "redis", "ci/cd", "kubernetes"],
    },
    "Mobile Engineer": {
        "industry": "Software Engineering",
        "description": "Build native or cross-platform mobile apps for iOS and Android.",
        "avg_salary": 118000, "growth": "+20%",
        "required":     ["swift", "kotlin", "mobile development", "git"],
        "important":    ["react native", "rest api", "xcode", "android studio"],
        "nice_to_have": ["flutter", "ci/cd", "app store deployment", "firebase"],
    },
    "DevOps Engineer": {
        "industry": "Software Engineering",
        "description": "Automate software delivery pipelines and manage cloud infrastructure.",
        "avg_salary": 120000, "growth": "+27%",
        "required":     ["linux", "docker", "ci/cd", "git"],
        "important":    ["kubernetes", "aws", "terraform", "bash scripting"],
        "nice_to_have": ["ansible", "prometheus", "grafana", "python", "jenkins"],
    },
    "Site Reliability Engineer": {
        "industry": "Software Engineering",
        "description": "Ensure reliability, uptime, and performance of large-scale production systems.",
        "avg_salary": 130000, "growth": "+28%",
        "required":     ["linux", "python", "monitoring", "incident management"],
        "important":    ["kubernetes", "docker", "aws", "prometheus", "grafana"],
        "nice_to_have": ["go", "distributed systems", "terraform", "chaos engineering"],
    },
    "Cybersecurity Engineer": {
        "industry": "Software Engineering",
        "description": "Protect systems and data from threats through security architecture and incident response.",
        "avg_salary": 125000, "growth": "+33%",
        "required":     ["cybersecurity", "network security", "linux", "incident response"],
        "important":    ["python", "vulnerability assessment", "siem", "cloud security"],
        "nice_to_have": ["penetration testing", "aws", "forensics", "compliance", "scripting"],
    },
    "Cloud Architect": {
        "industry": "Software Engineering",
        "description": "Design scalable, reliable cloud infrastructure and migration strategies.",
        "avg_salary": 150000, "growth": "+38%",
        "required":     ["aws", "cloud computing", "architecture", "infrastructure as code"],
        "important":    ["terraform", "kubernetes", "docker", "networking", "security"],
        "nice_to_have": ["gcp", "azure", "cost optimization", "microservices", "python"],
    },
    "Embedded Systems Engineer": {
        "industry": "Software Engineering",
        "description": "Write firmware and low-level software for hardware devices and microcontrollers.",
        "avg_salary": 105000, "growth": "+15%",
        "required":     ["c", "c++", "embedded systems", "microcontrollers"],
        "important":    ["rtos", "hardware debugging", "linux", "communication protocols"],
        "nice_to_have": ["python", "fpga", "iot", "robotics", "assembly"],
    },
    "Blockchain Developer": {
        "industry": "Software Engineering",
        "description": "Build smart contracts and decentralized applications on blockchain platforms.",
        "avg_salary": 120000, "growth": "+20%",
        "required":     ["solidity", "blockchain", "smart contracts", "javascript"],
        "important":    ["web3", "ethereum", "python", "git"],
        "nice_to_have": ["defi", "nft", "rust", "cryptography", "security auditing"],
    },

    # ── BUSINESS & FINANCE ────────────────────────────────────────────────────
    "Financial Analyst": {
        "industry": "Business & Finance",
        "description": "Analyze financial data, build models, and provide investment or operational insights.",
        "avg_salary": 85000, "growth": "+9%",
        "required":     ["financial modeling", "excel", "financial analysis", "accounting"],
        "important":    ["sql", "valuation", "forecasting", "powerpoint", "bloomberg"],
        "nice_to_have": ["python", "vba", "tableau", "cfa", "erp systems"],
    },
    "Investment Banker": {
        "industry": "Business & Finance",
        "description": "Execute M&A transactions, IPOs, and capital raises for corporate clients.",
        "avg_salary": 130000, "growth": "+7%",
        "required":     ["financial modeling", "valuation", "excel", "deal structuring"],
        "important":    ["accounting", "powerpoint", "pitchbook", "due diligence", "dcf"],
        "nice_to_have": ["sql", "bloomberg", "lbo modeling", "python", "series 79"],
    },
    "Investment Analyst (Buy-Side)": {
        "industry": "Business & Finance",
        "description": "Research and select investments for hedge funds, mutual funds, or endowments.",
        "avg_salary": 110000, "growth": "+8%",
        "required":     ["financial modeling", "equity research", "valuation", "excel"],
        "important":    ["python", "bloomberg", "sql", "portfolio management"],
        "nice_to_have": ["cfa", "r", "machine learning", "alternative data"],
    },
    "Accountant": {
        "industry": "Business & Finance",
        "description": "Manage financial records, prepare statements, and ensure tax compliance.",
        "avg_salary": 72000, "growth": "+6%",
        "required":     ["accounting", "gaap", "excel", "financial reporting"],
        "important":    ["quickbooks", "tax preparation", "auditing", "erp systems"],
        "nice_to_have": ["cpa", "sql", "payroll", "budgeting", "power bi"],
    },
    "Corporate Finance Manager": {
        "industry": "Business & Finance",
        "description": "Oversee budgeting, forecasting, and capital allocation strategy.",
        "avg_salary": 115000, "growth": "+10%",
        "required":     ["financial modeling", "budgeting", "forecasting", "excel"],
        "important":    ["accounting", "erp systems", "leadership", "stakeholder management"],
        "nice_to_have": ["sql", "tableau", "mba", "strategic planning"],
    },
    "Risk Analyst": {
        "industry": "Business & Finance",
        "description": "Identify, assess, and mitigate financial and operational risks.",
        "avg_salary": 88000, "growth": "+12%",
        "required":     ["risk management", "financial modeling", "excel", "statistics"],
        "important":    ["sql", "python", "regulatory compliance", "stress testing"],
        "nice_to_have": ["r", "machine learning", "frm", "bloomberg", "monte carlo"],
    },
    "Actuary": {
        "industry": "Business & Finance",
        "description": "Use math and statistics to assess financial risk for insurance and pensions.",
        "avg_salary": 105000, "growth": "+21%",
        "required":     ["actuarial science", "statistics", "probability", "excel"],
        "important":    ["r", "sas", "financial modeling", "actuarial exams"],
        "nice_to_have": ["python", "machine learning", "sql", "communication"],
    },
    "Management Consultant": {
        "industry": "Business & Finance",
        "description": "Solve complex business problems for clients across industries.",
        "avg_salary": 105000, "growth": "+14%",
        "required":     ["problem solving", "communication", "data analysis", "powerpoint"],
        "important":    ["excel", "project management", "stakeholder management", "strategy"],
        "nice_to_have": ["sql", "python", "mba", "industry expertise"],
    },
    "Supply Chain Manager": {
        "industry": "Business & Finance",
        "description": "Optimize end-to-end supply chain operations from procurement to delivery.",
        "avg_salary": 92000, "growth": "+11%",
        "required":     ["supply chain management", "logistics", "inventory management", "excel"],
        "important":    ["erp systems", "data analysis", "vendor management", "forecasting"],
        "nice_to_have": ["sql", "lean", "six sigma", "python", "sap"],
    },
    "Operations Manager": {
        "industry": "Business & Finance",
        "description": "Drive efficiency and performance across an organization's core operations.",
        "avg_salary": 88000, "growth": "+9%",
        "required":     ["operations management", "project management", "leadership", "process improvement"],
        "important":    ["excel", "data analysis", "budgeting", "team management"],
        "nice_to_have": ["lean", "six sigma", "erp systems", "sql", "kpi management"],
    },
    "Product Manager": {
        "industry": "Business & Finance",
        "description": "Define and execute the vision for a product by balancing user needs and business goals.",
        "avg_salary": 120000, "growth": "+19%",
        "required":     ["product management", "roadmapping", "user research", "stakeholder management"],
        "important":    ["data analysis", "sql", "agile", "communication", "a/b testing"],
        "nice_to_have": ["python", "ux design", "sql", "machine learning", "technical writing"],
    },
    "Entrepreneur / Startup Founder": {
        "industry": "Business & Finance",
        "description": "Build and scale a company from idea to product-market fit and beyond.",
        "avg_salary": 85000, "growth": "+25%",
        "required":     ["entrepreneurship", "product development", "fundraising", "leadership"],
        "important":    ["financial modeling", "marketing", "sales", "communication"],
        "nice_to_have": ["python", "no-code tools", "growth hacking", "pitch decks"],
    },

    # ── HEALTHCARE & MEDICINE ─────────────────────────────────────────────────
    "Registered Nurse": {
        "industry": "Healthcare",
        "description": "Provide direct patient care, administer medications, and support physicians.",
        "avg_salary": 77000, "growth": "+6%",
        "required":     ["nursing", "patient care", "clinical assessment", "ehr systems"],
        "important":    ["bls certification", "medication administration", "critical thinking", "communication"],
        "nice_to_have": ["acls", "specialty certifications", "charge nurse experience", "leadership"],
    },
    "Physician Assistant": {
        "industry": "Healthcare",
        "description": "Examine patients, diagnose illnesses, and develop treatment plans under physician supervision.",
        "avg_salary": 121000, "growth": "+28%",
        "required":     ["clinical medicine", "physical examination", "diagnosis", "treatment planning"],
        "important":    ["ehr systems", "pharmacology", "patient communication", "evidence-based medicine"],
        "nice_to_have": ["specialty experience", "research", "leadership", "procedure skills"],
    },
    "Physical Therapist": {
        "industry": "Healthcare",
        "description": "Restore mobility and manage pain in patients through therapeutic exercise.",
        "avg_salary": 92000, "growth": "+17%",
        "required":     ["physical therapy", "rehabilitation", "anatomy", "patient assessment"],
        "important":    ["exercise prescription", "manual therapy", "documentation", "communication"],
        "nice_to_have": ["sports medicine", "dry needling", "aquatic therapy", "research"],
    },
    "Healthcare Administrator": {
        "industry": "Healthcare",
        "description": "Manage healthcare facilities, staff, budgets, and regulatory compliance.",
        "avg_salary": 100000, "growth": "+28%",
        "required":     ["healthcare management", "budgeting", "regulatory compliance", "leadership"],
        "important":    ["ehr systems", "data analysis", "project management", "communication"],
        "nice_to_have": ["healthcare policy", "lean healthcare", "quality improvement", "mba"],
    },
    "Clinical Data Analyst": {
        "industry": "Healthcare",
        "description": "Analyze clinical trial and patient data to support medical research and operations.",
        "avg_salary": 85000, "growth": "+22%",
        "required":     ["sql", "data analysis", "clinical research", "statistics"],
        "important":    ["python", "excel", "sas", "ehr systems", "data visualization"],
        "nice_to_have": ["r", "machine learning", "regulatory submissions", "tableau"],
    },
    "Pharmacist": {
        "industry": "Healthcare",
        "description": "Dispense medications, counsel patients, and ensure drug safety.",
        "avg_salary": 125000, "growth": "+2%",
        "required":     ["pharmacology", "medication dispensing", "drug interactions", "patient counseling"],
        "important":    ["pharmacy software", "regulatory compliance", "clinical knowledge", "communication"],
        "nice_to_have": ["specialty certifications", "research", "leadership", "mtm"],
    },
    "Mental Health Counselor": {
        "industry": "Healthcare",
        "description": "Provide therapy and counseling to individuals dealing with mental health challenges.",
        "avg_salary": 57000, "growth": "+22%",
        "required":     ["counseling", "psychotherapy", "mental health assessment", "case management"],
        "important":    ["cbt", "crisis intervention", "documentation", "empathy"],
        "nice_to_have": ["trauma-informed care", "group therapy", "dbt", "supervisory experience"],
    },
    "Biomedical Engineer": {
        "industry": "Healthcare",
        "description": "Design and develop medical devices, equipment, and diagnostic tools.",
        "avg_salary": 97000, "growth": "+10%",
        "required":     ["biomedical engineering", "medical devices", "regulatory compliance", "engineering design"],
        "important":    ["matlab", "fda regulations", "prototyping", "testing"],
        "nice_to_have": ["python", "3d modeling", "signal processing", "clinical trials"],
    },

    # ── LAW & POLICY ──────────────────────────────────────────────────────────
    "Attorney": {
        "industry": "Law & Policy",
        "description": "Represent clients in legal matters, draft contracts, and provide legal counsel.",
        "avg_salary": 126000, "growth": "+10%",
        "required":     ["legal research", "legal writing", "litigation", "client counseling"],
        "important":    ["negotiation", "contract drafting", "court procedures", "bar admission"],
        "nice_to_have": ["specific practice area expertise", "business development", "legal tech", "trial experience"],
    },
    "Paralegal": {
        "industry": "Law & Policy",
        "description": "Support attorneys through legal research, drafting, and case management.",
        "avg_salary": 57000, "growth": "+12%",
        "required":     ["legal research", "legal writing", "case management", "document review"],
        "important":    ["westlaw", "lexisnexis", "microsoft office", "organization"],
        "nice_to_have": ["e-discovery", "paralegal certification", "specialty area knowledge"],
    },
    "Compliance Officer": {
        "industry": "Law & Policy",
        "description": "Ensure an organization adheres to laws, regulations, and internal policies.",
        "avg_salary": 92000, "growth": "+13%",
        "required":     ["regulatory compliance", "risk management", "policy development", "auditing"],
        "important":    ["data analysis", "excel", "communication", "legal research"],
        "nice_to_have": ["sql", "fintech regulations", "healthcare compliance", "cfe certification"],
    },
    "Policy Analyst": {
        "industry": "Law & Policy",
        "description": "Research and evaluate public policies to inform government or nonprofit decision-making.",
        "avg_salary": 68000, "growth": "+6%",
        "required":     ["policy research", "data analysis", "writing", "quantitative analysis"],
        "important":    ["statistics", "excel", "stakeholder communication", "policy writing"],
        "nice_to_have": ["r", "python", "gis", "economics", "public speaking"],
    },
    "Contract Manager": {
        "industry": "Law & Policy",
        "description": "Manage the full lifecycle of contracts from drafting to renewals and disputes.",
        "avg_salary": 82000, "growth": "+8%",
        "required":     ["contract management", "negotiation", "legal writing", "risk management"],
        "important":    ["procurement", "vendor management", "erp systems", "communication"],
        "nice_to_have": ["contract management software", "legal knowledge", "project management"],
    },

    # ── CREATIVE & MARKETING ──────────────────────────────────────────────────
    "UX Designer": {
        "industry": "Creative & Marketing",
        "description": "Design intuitive user experiences through research, wireframing, and prototyping.",
        "avg_salary": 95000, "growth": "+23%",
        "required":     ["ux design", "user research", "wireframing", "prototyping"],
        "important":    ["figma", "usability testing", "information architecture", "visual design"],
        "nice_to_have": ["html", "css", "motion design", "accessibility", "design systems"],
    },
    "Graphic Designer": {
        "industry": "Creative & Marketing",
        "description": "Create visual content for branding, marketing, and digital products.",
        "avg_salary": 57000, "growth": "+3%",
        "required":     ["graphic design", "adobe photoshop", "adobe illustrator", "typography"],
        "important":    ["branding", "layout design", "indesign", "color theory"],
        "nice_to_have": ["motion graphics", "figma", "after effects", "web design", "3d design"],
    },
    "Content Strategist": {
        "industry": "Creative & Marketing",
        "description": "Plan and manage content that drives awareness, engagement, and conversion.",
        "avg_salary": 72000, "growth": "+12%",
        "required":     ["content strategy", "writing", "seo", "content marketing"],
        "important":    ["analytics", "editorial planning", "social media", "email marketing"],
        "nice_to_have": ["google analytics", "cms platforms", "video scripting", "copywriting"],
    },
    "Digital Marketing Manager": {
        "industry": "Creative & Marketing",
        "description": "Plan and execute digital campaigns across paid, owned, and earned channels.",
        "avg_salary": 82000, "growth": "+10%",
        "required":     ["digital marketing", "seo", "sem", "data analysis"],
        "important":    ["google ads", "facebook ads", "google analytics", "email marketing"],
        "nice_to_have": ["marketing automation", "a/b testing", "sql", "python", "crm"],
    },
    "Brand Manager": {
        "industry": "Creative & Marketing",
        "description": "Define and protect a brand's identity and positioning in the market.",
        "avg_salary": 88000, "growth": "+8%",
        "required":     ["brand management", "marketing strategy", "communication", "project management"],
        "important":    ["market research", "data analysis", "excel", "advertising"],
        "nice_to_have": ["digital marketing", "social media", "consumer insights", "budget management"],
    },
    "SEO Specialist": {
        "industry": "Creative & Marketing",
        "description": "Improve organic search visibility through technical and content-driven strategies.",
        "avg_salary": 65000, "growth": "+8%",
        "required":     ["seo", "keyword research", "google analytics", "content optimization"],
        "important":    ["technical seo", "link building", "html", "data analysis"],
        "nice_to_have": ["python", "sql", "semrush", "ahrefs", "javascript"],
    },
    "Copywriter": {
        "industry": "Creative & Marketing",
        "description": "Write persuasive marketing copy for ads, websites, email campaigns, and more.",
        "avg_salary": 62000, "growth": "+6%",
        "required":     ["copywriting", "writing", "advertising", "brand voice"],
        "important":    ["seo", "email marketing", "content strategy", "editing"],
        "nice_to_have": ["social media", "video scripts", "html", "analytics"],
    },
    "Public Relations Manager": {
        "industry": "Creative & Marketing",
        "description": "Manage an organization's public image through media relations and communications.",
        "avg_salary": 78000, "growth": "+6%",
        "required":     ["public relations", "media relations", "writing", "communication"],
        "important":    ["crisis communication", "social media", "press releases", "stakeholder management"],
        "nice_to_have": ["analytics", "video production", "event management", "marketing"],
    },
    "Video Producer": {
        "industry": "Creative & Marketing",
        "description": "Plan, shoot, and edit video content for marketing, education, and entertainment.",
        "avg_salary": 65000, "growth": "+10%",
        "required":     ["video production", "video editing", "storytelling", "premiere pro"],
        "important":    ["after effects", "cinematography", "scriptwriting", "color grading"],
        "nice_to_have": ["motion graphics", "social media", "youtube optimization", "3d animation"],
    },

    # ── TRADITIONAL ENGINEERING ───────────────────────────────────────────────
    "Mechanical Engineer": {
        "industry": "Traditional Engineering",
        "description": "Design and analyze mechanical systems, machines, and physical products.",
        "avg_salary": 88000, "growth": "+11%",
        "required":     ["mechanical engineering", "cad", "solidworks", "engineering design"],
        "important":    ["fea analysis", "manufacturing", "thermodynamics", "matlab"],
        "nice_to_have": ["3d printing", "python", "robotics", "project management", "gd&t"],
    },
    "Civil Engineer": {
        "industry": "Traditional Engineering",
        "description": "Design and oversee construction of infrastructure: roads, bridges, buildings.",
        "avg_salary": 87000, "growth": "+8%",
        "required":     ["civil engineering", "structural analysis", "autocad", "engineering design"],
        "important":    ["project management", "construction management", "geotechnical", "hydraulics"],
        "nice_to_have": ["revit", "gis", "environmental compliance", "bim", "land development"],
    },
    "Electrical Engineer": {
        "industry": "Traditional Engineering",
        "description": "Design electrical systems, circuits, and power infrastructure.",
        "avg_salary": 98000, "growth": "+9%",
        "required":     ["electrical engineering", "circuit design", "power systems", "autocad"],
        "important":    ["matlab", "plc programming", "signal processing", "testing"],
        "nice_to_have": ["embedded systems", "python", "pcb design", "renewable energy"],
    },
    "Chemical Engineer": {
        "industry": "Traditional Engineering",
        "description": "Design processes to safely transform chemicals into useful products.",
        "avg_salary": 103000, "growth": "+9%",
        "required":     ["chemical engineering", "process design", "thermodynamics", "safety"],
        "important":    ["matlab", "aspen", "project management", "data analysis"],
        "nice_to_have": ["python", "six sigma", "environmental regulations", "pilot plant"],
    },
    "Aerospace Engineer": {
        "industry": "Traditional Engineering",
        "description": "Design and test aircraft, spacecraft, and propulsion systems.",
        "avg_salary": 118000, "growth": "+8%",
        "required":     ["aerospace engineering", "aerodynamics", "matlab", "engineering design"],
        "important":    ["cad", "computational fluid dynamics", "systems engineering", "testing"],
        "nice_to_have": ["python", "fea", "propulsion", "avionics", "systems integration"],
    },
    "Environmental Engineer": {
        "industry": "Traditional Engineering",
        "description": "Develop solutions to environmental problems: pollution, remediation, sustainability.",
        "avg_salary": 88000, "growth": "+4%",
        "required":     ["environmental engineering", "regulatory compliance", "data analysis", "report writing"],
        "important":    ["gis", "environmental modeling", "project management", "autocad"],
        "nice_to_have": ["python", "sustainability", "eia", "remediation design"],
    },
    "Manufacturing Engineer": {
        "industry": "Traditional Engineering",
        "description": "Optimize manufacturing processes for quality, efficiency, and cost.",
        "avg_salary": 85000, "growth": "+8%",
        "required":     ["manufacturing engineering", "process improvement", "quality control", "lean"],
        "important":    ["cad", "six sigma", "erp systems", "data analysis"],
        "nice_to_have": ["plc programming", "automation", "3d printing", "python", "solidworks"],
    },
    "Structural Engineer": {
        "industry": "Traditional Engineering",
        "description": "Analyze and design structures to safely bear loads and resist forces.",
        "avg_salary": 89000, "growth": "+7%",
        "required":     ["structural engineering", "structural analysis", "autocad", "building codes"],
        "important":    ["revit", "fea analysis", "project management", "construction"],
        "nice_to_have": ["bim", "python", "seismic design", "pe license"],
    },

    # ── EDUCATION ──────────────────────────────────────────────────────────────
    "K-12 Teacher": {
        "industry": "Education",
        "description": "Educate students in core subjects while fostering development and critical thinking.",
        "avg_salary": 62000, "growth": "+5%",
        "required":     ["teaching", "curriculum development", "classroom management", "lesson planning"],
        "important":    ["communication", "assessment", "student engagement", "educational technology"],
        "nice_to_have": ["special education", "differentiated instruction", "ib/ap experience", "coaching"],
    },
    "University Professor": {
        "industry": "Education",
        "description": "Teach undergraduate and graduate courses while conducting original research.",
        "avg_salary": 82000, "growth": "+6%",
        "required":     ["subject matter expertise", "teaching", "research", "academic writing"],
        "important":    ["grant writing", "curriculum development", "mentoring", "publications"],
        "nice_to_have": ["tenure track experience", "online teaching", "interdisciplinary research"],
    },
    "Instructional Designer": {
        "industry": "Education",
        "description": "Design learning experiences and courses for corporate or academic settings.",
        "avg_salary": 72000, "growth": "+11%",
        "required":     ["instructional design", "curriculum development", "adult learning theory", "e-learning"],
        "important":    ["articulate storyline", "lms", "needs assessment", "visual design"],
        "nice_to_have": ["video production", "html", "project management", "gamification"],
    },
    "Corporate Trainer": {
        "industry": "Education",
        "description": "Develop and deliver training programs for employee skills development.",
        "avg_salary": 68000, "growth": "+9%",
        "required":     ["training delivery", "facilitation", "curriculum development", "needs assessment"],
        "important":    ["e-learning", "presentation", "communication", "instructional design"],
        "nice_to_have": ["lms", "coaching", "data analysis", "project management"],
    },
    "Education Technology Specialist": {
        "industry": "Education",
        "description": "Integrate technology into learning environments to improve outcomes.",
        "avg_salary": 70000, "growth": "+15%",
        "required":     ["educational technology", "lms", "training", "technical support"],
        "important":    ["instructional design", "data analysis", "communication", "project management"],
        "nice_to_have": ["programming", "video production", "accessibility", "google workspace"],
    },

    # ── OPERATIONS & HUMAN RESOURCES ─────────────────────────────────────────
    "Human Resources Manager": {
        "industry": "Operations & HR",
        "description": "Oversee talent acquisition, employee relations, and HR strategy.",
        "avg_salary": 80000, "growth": "+9%",
        "required":     ["human resources", "talent acquisition", "employee relations", "hr policy"],
        "important":    ["hris systems", "performance management", "communication", "compliance"],
        "nice_to_have": ["data analysis", "excel", "coaching", "compensation analysis", "shrm certification"],
    },
    "Recruiter": {
        "industry": "Operations & HR",
        "description": "Source, screen, and place candidates across roles and industries.",
        "avg_salary": 62000, "growth": "+6%",
        "required":     ["recruiting", "talent acquisition", "interviewing", "candidate sourcing"],
        "important":    ["ats", "communication", "linkedin recruiting", "employer branding"],
        "nice_to_have": ["boolean search", "diversity recruiting", "data analysis", "crm"],
    },
    "Project Manager": {
        "industry": "Operations & HR",
        "description": "Plan, execute, and close projects on time, on scope, and on budget.",
        "avg_salary": 90000, "growth": "+15%",
        "required":     ["project management", "planning", "risk management", "stakeholder management"],
        "important":    ["agile", "scrum", "budget management", "communication", "ms project"],
        "nice_to_have": ["pmp certification", "data analysis", "excel", "jira", "leadership"],
    },
    "Logistics Manager": {
        "industry": "Operations & HR",
        "description": "Manage transportation, distribution, and warehousing operations.",
        "avg_salary": 78000, "growth": "+7%",
        "required":     ["logistics", "supply chain", "operations management", "vendor management"],
        "important":    ["erp systems", "data analysis", "excel", "warehouse management"],
        "nice_to_have": ["sql", "lean", "import/export regulations", "six sigma"],
    },
}

