"""
Career Matching Engine
----------------------
Scores a user's skills against each career path.
Uses data-derived weights from computed_weights.json if available,
falls back to hand-crafted weights in career_paths.py.

Scoring formula:
  - Each required skill matched:    3 points
  - Each important skill matched:   2 points
  - Each nice_to_have matched:      1 point
  - Score = (points earned / max possible points) x 100
"""

import sys, os, json
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from matching_engine.career_paths import CAREER_PATHS

# Load data-derived weights if available (generated by compute_weights.py)
_computed_path = os.path.join(os.path.dirname(__file__), "computed_weights.json")
_computed = None
if os.path.exists(_computed_path):
    with open(_computed_path) as f:
        _computed = json.load(f)
    print(f"[matcher] Using data-driven weights from {len(_computed)} career paths.")


def _get_career_def(career_name: str) -> dict:
    """Returns computed weights if available, falls back to hand-crafted."""
    if _computed and career_name in _computed:
        c = _computed[career_name]
        base = CAREER_PATHS[career_name].copy()
        base["required"]      = c["required"]
        base["important"]     = c["important"]
        base["nice_to_have"]  = c["nice_to_have"]
        base["data_driven"]   = True
        base["jobs_analyzed"] = c["total_jobs_analyzed"]
        return base
    return {**CAREER_PATHS.get(career_name, {}), "data_driven": False, "jobs_analyzed": 0}


def score_career(user_skills: list, career: dict) -> dict:
    """Score a user against a single career path definition."""
    user_set = set(s.lower() for s in user_skills)
    weights = {"required": 3, "important": 2, "nice_to_have": 1}
    total_possible = 0
    total_earned = 0
    matched = []
    missing = {"required": [], "important": [], "nice_to_have": []}

    for tier, weight in weights.items():
        for skill in career.get(tier, []):
            total_possible += weight
            if skill.lower() in user_set:
                total_earned += weight
                matched.append(skill)
            else:
                missing[tier].append(skill)

    score = round((total_earned / total_possible) * 100) if total_possible > 0 else 0
    return {
        "score": score,
        "matched_skills": matched,
        "missing_required": missing["required"],
        "missing_important": missing["important"],
        "missing_nice_to_have": missing["nice_to_have"],
    }


def match_all_careers(user_skills: list) -> list:
    """
    Score user skills against all career paths.
    Uses data-derived weights when computed_weights.json exists.
    Returns sorted list (highest match first).
    """
    results = []
    for career_title in CAREER_PATHS.keys():
        career_data = _get_career_def(career_title)
        score_data  = score_career(user_skills, career_data)
        results.append({
            "career":           career_title,
            "score":            score_data["score"],
            "avg_salary":       career_data["avg_salary"],
            "growth":           career_data["growth"],
            "description":      career_data["description"],
            "matched_skills":   score_data["matched_skills"],
            "missing_required": score_data["missing_required"],
            "missing_important":score_data["missing_important"],
            "missing_nice_to_have": score_data["missing_nice_to_have"],
            "total_required":   len(career_data.get("required", [])),
            "matched_required": len(career_data.get("required", [])) - len(score_data["missing_required"]),
            "data_driven":      career_data.get("data_driven", False),
            "jobs_analyzed":    career_data.get("jobs_analyzed", 0),
        })
    return sorted(results, key=lambda x: x["score"], reverse=True)


def get_gap_analysis(user_skills: list, career_title: str) -> dict:
    """Deep gap analysis for a specific career."""
    career = _get_career_def(career_title)
    if not career.get("avg_salary"):
        return {"error": f"Career '{career_title}' not found."}

    score_data   = score_career(user_skills, career)
    priority_gaps = (
        score_data["missing_required"] +
        score_data["missing_important"] +
        score_data["missing_nice_to_have"]
    )
    return {
        "career":            career_title,
        "match_score":       score_data["score"],
        "description":       career["description"],
        "avg_salary":        career["avg_salary"],
        "growth":            career["growth"],
        "you_have":          score_data["matched_skills"],
        "missing_required":  score_data["missing_required"],
        "missing_important": score_data["missing_important"],
        "missing_nice_to_have": score_data["missing_nice_to_have"],
        "priority_gaps":     priority_gaps,
        "total_gaps":        len(priority_gaps),
        "data_driven":       career.get("data_driven", False),
        "jobs_analyzed":     career.get("jobs_analyzed", 0),
    }


if __name__ == "__main__":
    user_skills = ["python", "java", "sql", "excel", "git", "tableau", "power bi"]
    print("=== Career Match Results ===\n")
    matches = match_all_careers(user_skills)
    for m in matches[:5]:
        driven = "📊 data-driven" if m["data_driven"] else "✏️  hand-crafted"
        print(f"  {m['score']:>3}%  {m['career']:<25}  ${m['avg_salary']:,}  {driven}")

    print("\n=== Gap Analysis: Data Scientist ===\n")
    gap = get_gap_analysis(user_skills, "Data Scientist")
    print(json.dumps(gap, indent=2))
