"""
Skills Taxonomy — CareerIQ
---------------------------
400+ skills the platform recognizes across every industry.
The resume parser scans for these (and their aliases).
To add a skill: add it to the right category.
"""

SKILLS_TAXONOMY = {

    # ── PROGRAMMING ───────────────────────────────────────────────────────────
    "programming": [
        "python", "r", "java", "javascript", "typescript", "c++", "c#",
        "scala", "go", "rust", "swift", "kotlin", "matlab", "julia", "ruby",
        "php", "bash", "shell scripting", "perl", "haskell", "elixir",
        "dart", "flutter", "node.js", "solidity",
    ],

    # ── DATA & ANALYTICS ──────────────────────────────────────────────────────
    "data_and_analytics": [
        "sql", "mysql", "postgresql", "sqlite", "nosql", "mongodb", "redis",
        "pandas", "numpy", "dplyr", "excel", "google sheets", "power bi",
        "tableau", "looker", "metabase", "qlik", "data studio", "superset",
        "data analysis", "data visualization", "statistical analysis",
        "exploratory data analysis", "eda", "a/b testing", "hypothesis testing",
        "data warehousing", "data warehouse", "data modeling", "data pipeline",
        "etl", "business intelligence", "reporting", "kpi management",
        "quantitative analysis", "market research", "competitive analysis",
        "alternative data",
        "analytics",
        "data structures",
        "sas",
    ],

    # ── MACHINE LEARNING & AI ─────────────────────────────────────────────────
    "machine_learning": [
        "machine learning", "deep learning", "neural networks", "nlp",
        "natural language processing", "computer vision", "reinforcement learning",
        "scikit-learn", "tensorflow", "pytorch", "keras", "xgboost", "lightgbm",
        "random forest", "gradient boosting", "regression", "classification",
        "clustering", "feature engineering", "model deployment", "mlops",
        "hugging face", "transformers", "llm", "large language models",
        "generative ai", "prompt engineering", "rag", "fine-tuning",
        "opencv", "cuda", "time series", "forecasting",
    ],

    # ── CLOUD & DEVOPS ────────────────────────────────────────────────────────
    "cloud_and_devops": [
        "aws", "azure", "gcp", "google cloud", "cloud computing",
        "docker", "kubernetes", "terraform", "ci/cd", "devops",
        "git", "github", "gitlab", "linux", "unix", "rest api",
        "microservices", "serverless", "lambda", "airflow", "spark",
        "hadoop", "kafka", "databricks", "snowflake", "dbt",
        "data lake", "infrastructure as code", "ansible", "jenkins",
        "prometheus", "grafana", "monitoring", "incident management",
        "bash scripting", "networking", "security", "cloud security",
        "chaos engineering",
        "cost optimization",
        "cryptography",
        "cybersecurity",
        "distributed systems",
        "forensics",
        "grpc",
        "incident response",
        "network security",
        "penetration testing",
        "scripting",
        "security auditing",
        "siem",
        "vulnerability assessment",
    ],

    # ── STATISTICS & MATH ─────────────────────────────────────────────────────
    "statistics_and_math": [
        "statistics", "probability", "linear algebra", "calculus",
        "bayesian statistics", "statistical modeling", "regression analysis",
        "simulation", "monte carlo", "optimization", "actuarial science",
        "actuarial exams", "research methodology", "experimental design",
    ],

    # ── WEB & MOBILE ──────────────────────────────────────────────────────────
    "web_and_mobile": [
        "html", "css", "react", "vue", "angular", "svelte", "webpack",
        "responsive design", "accessibility", "web development",
        "mobile development", "react native", "xcode", "android studio",
        "firebase", "app store deployment", "web3", "ethereum",
        "smart contracts", "blockchain",
        "3d animation",
        "3d design",
        "defi",
        "motion design",
        "nft",
        "web design",
    ],

    # ── BUSINESS & STRATEGY ───────────────────────────────────────────────────
    "business_and_strategy": [
        "project management", "agile", "scrum", "product management",
        "business analysis", "requirements gathering", "stakeholder management",
        "communication", "presentation", "critical thinking", "problem solving",
        "leadership", "teamwork", "strategy", "consulting", "financial modeling",
        "budgeting", "forecasting", "financial analysis", "financial reporting",
        "valuation", "accounting", "gaap", "auditing", "tax preparation",
        "risk management", "compliance", "regulatory compliance",
        "supply chain management", "logistics", "inventory management",
        "operations management", "process improvement", "lean", "six sigma",
        "erp systems", "sap", "vendor management", "procurement",
        "entrepreneurship", "product development", "fundraising",
        "pitching", "pitch decks", "business development", "sales",
        "negotiation", "contract management", "deal structuring",
        "portfolio management", "equity research", "due diligence",
        "lbo modeling", "dcf", "bloomberg", "vba",
        "budget management",
        "cfa",
        "cms platforms",
        "contract management software",
        "documentation",
        "economics",
        "frm",
        "google workspace",
        "import/export regulations",
        "industry expertise",
        "jira",
        "marketing",
        "mba",
        "microsoft office",
        "ms project",
        "no-code tools",
        "payroll",
        "pitchbook",
        "planning",
        "pmp certification",
        "powerpoint",
        "process mapping",
        "programming",
        "quickbooks",
        "series 79",
        "stakeholder communication",
        "strategic planning",
        "stress testing",
        "supply chain",
        "team management",
        "warehouse management",
    ],

    # ── DESIGN & CREATIVE ─────────────────────────────────────────────────────
    "design_and_creative": [
        "ux design", "ui design", "user research", "wireframing", "prototyping",
        "figma", "sketch", "invision", "usability testing", "information architecture",
        "visual design", "graphic design", "adobe photoshop", "adobe illustrator",
        "indesign", "typography", "color theory", "branding", "layout design",
        "motion graphics", "after effects", "premiere pro", "video editing",
        "video production", "cinematography", "color grading", "3d modeling",
        "solidworks", "autocad", "revit", "cad", "design systems",
        "storytelling", "scriptwriting",
        "brand voice",
        "content optimization",
        "editorial planning",
        "video scripting",
        "video scripts",
        "youtube optimization",
    ],

    # ── MARKETING & COMMUNICATIONS ────────────────────────────────────────────
    "marketing_and_communications": [
        "digital marketing", "content marketing", "content strategy",
        "seo", "sem", "google ads", "facebook ads", "email marketing",
        "social media", "brand management", "marketing strategy",
        "copywriting", "writing", "editing", "technical writing",
        "public relations", "media relations", "press releases",
        "crisis communication", "advertising", "market research",
        "consumer insights", "a/b testing", "growth hacking",
        "marketing automation", "crm", "google analytics", "keyword research",
        "link building", "semrush", "ahrefs",
        "event management",
        "technical seo",
    ],

    # ── ENGINEERING ───────────────────────────────────────────────────────────
    "engineering": [
        "mechanical engineering", "civil engineering", "electrical engineering",
        "chemical engineering", "aerospace engineering", "environmental engineering",
        "manufacturing engineering", "structural engineering", "biomedical engineering",
        "embedded systems", "microcontrollers", "rtos", "firmware",
        "engineering design", "fea analysis", "cfd", "thermodynamics",
        "hydraulics", "geotechnical", "structural analysis", "circuit design",
        "power systems", "signal processing", "plc programming",
        "process design", "process improvement", "quality control",
        "gd&t", "bim", "construction management", "land development",
        "environmental modeling", "remediation", "renewable energy",
        "aerodynamics", "systems engineering", "avionics", "propulsion",
        "robotics", "iot", "automation", "3d printing", "prototyping",
        "assembly", "fpga", "pcb design", "testing",
        "architecture",
        "aspen",
        "building codes",
        "communication protocols",
        "computational fluid dynamics",
        "construction",
        "eia",
        "environmental compliance",
        "environmental regulations",
        "fea",
        "gis",
        "hardware debugging",
        "manufacturing",
        "pe license",
        "pilot plant",
        "remediation design",
        "safety",
        "seismic design",
        "sustainability",
        "systems integration",
    ],

    # ── HEALTHCARE & CLINICAL ─────────────────────────────────────────────────
    "healthcare": [
        "nursing", "patient care", "clinical assessment", "ehr systems",
        "bls certification", "acls", "medication administration", "pharmacology",
        "physical therapy", "rehabilitation", "anatomy", "clinical medicine",
        "physical examination", "diagnosis", "treatment planning",
        "evidence-based medicine", "healthcare management", "healthcare policy",
        "clinical research", "medical devices", "fda regulations",
        "counseling", "psychotherapy", "mental health assessment",
        "cbt", "crisis intervention", "case management",
        "specialty certifications", "medication dispensing", "drug interactions",
        "patient counseling", "quality improvement", "lean healthcare",
        "aquatic therapy",
        "charge nurse experience",
        "clinical knowledge",
        "clinical trials",
        "dry needling",
        "empathy",
        "exercise prescription",
        "group therapy",
        "healthcare compliance",
        "manual therapy",
        "mtm",
        "patient assessment",
        "patient communication",
        "pharmacy software",
        "procedure skills",
        "regulatory submissions",
        "specialty experience",
        "sports medicine",
        "supervisory experience",
        "trauma-informed care",
    ],

    # ── LEGAL ─────────────────────────────────────────────────────────────────
    "legal": [
        "legal research", "legal writing", "litigation", "client counseling",
        "contract drafting", "bar admission", "westlaw", "lexisnexis",
        "e-discovery", "paralegal", "compliance", "policy research",
        "policy writing", "regulatory compliance", "risk management",
        "auditing", "cfe certification", "cpa", "contract management",
        "procurement", "due diligence",
        "court procedures",
        "document review",
        "fintech regulations",
        "legal knowledge",
        "legal tech",
        "paralegal certification",
        "policy development",
        "report writing",
        "specialty area knowledge",
        "specific practice area expertise",
        "trial experience",
    ],

    # ── EDUCATION ─────────────────────────────────────────────────────────────
    "education": [
        "teaching", "curriculum development", "classroom management",
        "lesson planning", "instructional design", "adult learning theory",
        "e-learning", "lms", "articulate storyline", "educational technology",
        "facilitation", "training delivery", "needs assessment",
        "assessment", "student engagement", "differentiated instruction",
        "mentoring", "coaching", "grant writing", "academic writing",
        "research", "publications",
        "gamification",
        "ib/ap experience",
        "interdisciplinary research",
        "online teaching",
        "special education",
        "subject matter expertise",
        "technical support",
        "tenure track experience",
        "training",
    ],

    # ── HR & PEOPLE OPS ───────────────────────────────────────────────────────
    "hr_and_people": [
        "human resources", "talent acquisition", "employee relations",
        "hr policy", "hris systems", "performance management",
        "compensation analysis", "diversity recruiting", "employer branding",
        "recruiting", "interviewing", "candidate sourcing", "ats",
        "linkedin recruiting", "shrm certification", "onboarding",
        "boolean search",
    ],

    # ── SOFT SKILLS (recognized in resumes) ───────────────────────────────────
    "soft_skills": [
        "communication", "leadership", "teamwork", "problem solving",
        "critical thinking", "time management", "organization",
        "adaptability", "creativity", "collaboration", "attention to detail",
        "data storytelling", "public speaking", "writing",
    ],
}

# Skill aliases: alternate terms that map to the canonical name above
SKILL_ALIASES = {
    "postgres": "postgresql",
    "ms sql": "sql",
    "t-sql": "sql",
    "mysql workbench": "mysql",
    "js": "javascript",
    "ts": "typescript",
    "node": "node.js",
    "nodejs": "node.js",
    "reactjs": "react",
    "vuejs": "vue",
    "angularjs": "angular",
    "sklearn": "scikit-learn",
    "sk-learn": "scikit-learn",
    "tf": "tensorflow",
    "hf": "hugging face",
    "llms": "large language models",
    "gpt": "large language models",
    "openai api": "large language models",
    "gen ai": "generative ai",
    "genai": "generative ai",
    "cv": "computer vision",
    "dl": "deep learning",
    "ml": "machine learning",
    "nlp": "natural language processing",
    "aws lambda": "lambda",
    "gcp": "google cloud",
    "google cloud platform": "google cloud",
    "microsoft azure": "azure",
    "k8s": "kubernetes",
    "gh actions": "ci/cd",
    "github actions": "ci/cd",
    "gitlab ci": "ci/cd",
    "jenkins ci": "ci/cd",
    "adobe xd": "ux design",
    "power bi desktop": "power bi",
    "ms excel": "excel",
    "microsoft excel": "excel",
    "google analytics 4": "google analytics",
    "ga4": "google analytics",
    "adwords": "google ads",
    "google adwords": "google ads",
    "fb ads": "facebook ads",
    "meta ads": "facebook ads",
    "revit architecture": "revit",
    "autodesk autocad": "autocad",
    "autodesk revit": "revit",
    "sw": "solidworks",
    "emr": "ehr systems",
    "electronic health records": "ehr systems",
    "electronic medical records": "ehr systems",
    "cbt therapy": "cbt",
    "cognitive behavioral therapy": "cbt",
    "physical exam": "physical examination",
    "critical care": "patient care",
    "westlaw edge": "westlaw",
    "lexis": "lexisnexis",
    "legal drafting": "contract drafting",
    "cad design": "cad",
    "computer aided design": "cad",
    "finite element analysis": "fea analysis",
    "fea": "fea analysis",
    "computational fluid dynamics": "cfd",
    "plc": "plc programming",
    "pid control": "process design",
    "lean manufacturing": "lean",
    "lean six sigma": "six sigma",
    "supply chain": "supply chain management",
    "scm": "supply chain management",
    "erp": "erp systems",
    "microsoft project": "project management",
    "ms project": "project management",
    "pmp": "project management",
    "prince2": "project management",
    "jira": "agile",
    "kanban": "agile",
    "safe agile": "agile",
    "product roadmap": "roadmapping",
    "strategic planning": "strategy",
    "business strategy": "strategy",
    "mergers and acquisitions": "deal structuring",
    "m&a": "deal structuring",
    "discounted cash flow": "dcf",
    "leveraged buyout": "lbo modeling",
    "ifrs": "gaap",
    "gaas": "auditing",
    "sox": "compliance",
    "gdpr": "regulatory compliance",
    "hipaa": "regulatory compliance",
    "aml": "compliance",
    "ux research": "user research",
    "usability": "usability testing",
    "wireframe": "wireframing",
    "mockup": "prototyping",
    "adobe premiere": "premiere pro",
    "final cut pro": "video editing",
    "davinci resolve": "color grading",
    "illustrator": "adobe illustrator",
    "photoshop": "adobe photoshop",
    "indd": "indesign",
    "sem / ppc": "sem",
    "pay per click": "sem",
    "ppc": "sem",
    "search engine optimization": "seo",
    "search engine marketing": "sem",
    "email campaigns": "email marketing",
    "mailchimp": "email marketing",
    "hubspot": "marketing automation",
    "salesforce": "crm",
    "sfdc": "crm",
    "curriculum design": "curriculum development",
    "lms administration": "lms",
    "blackboard": "lms",
    "canvas lms": "lms",
    "workday": "hris systems",
    "adp": "hris systems",
    "talent management": "talent acquisition",
    "people management": "leadership",
    "team management": "leadership",
}


# ── DERIVED LOOKUPS (built automatically — do not edit by hand) ───────────────
# SKILL_LOOKUP:    every recognizable term (canonical names + aliases) -> canonical name
# CATEGORY_LOOKUP: canonical skill name -> its taxonomy category
CATEGORY_LOOKUP = {}
SKILL_LOOKUP = {}

for _category, _skills in SKILLS_TAXONOMY.items():
    for _skill in _skills:
        CATEGORY_LOOKUP[_skill] = _category
        SKILL_LOOKUP[_skill] = _skill          # canonical maps to itself

# Aliases resolve to their canonical skill (and inherit its category)
for _alias, _canonical in SKILL_ALIASES.items():
    SKILL_LOOKUP[_alias] = _canonical
    if _canonical in CATEGORY_LOOKUP and _alias not in CATEGORY_LOOKUP:
        # alias category mirrors canonical (only used if alias is ever looked up directly)
        pass
